# Generated by Django 4.2.3 on 2023-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='name',
            new_name='Person_name',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='email',
            new_name='emailid',
        ),
        migrations.AddField(
            model_name='persons',
            name='age',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
